### ISSUE TITLE
Insert unicode char directly from panel

### ISSUE THREAD

**Issue by mg979** [randy3k/UnicodeCompletion#10]
Is it possible to make Unicode Lookup to insert the chosen character, even if Toggle is off? Or a similar panel to insert any Unicode character without having to toggle it first.

**Comment by randy3k** [comment]
You could just the command `Unicode Lookup`. It would copy the unicode to your chipboard so you just have to paste it into the position you want.

**Comment by mg979** [comment]
Understood, I wasn't aware of that, thanks.

**Comment by randy3k** [comment]
You could also try `Convert Selection to Unicodes`.

**Comment by mg979** [comment]
Thanks but I was just looking for a quick way to insert an Unicode char, without toggling it first, Lookup&paste is ok.
