### ISSUE TITLE
Unicode for X mark (and broken link in README)

### ISSUE THREAD

**Issue by reagle** [randy3k/UnicodeCompletion#11]
The link to the Julia Documentation in the README is 404. Also, I wish this had "✗" (U+2717) to match the checkmark that is provided "✓" (U+02713).

**Comment by randy3k** [comment]
Thanks for the report. The link is fixed.
You could use × (U+00D7) via `\times` meanwhile.

**Comment by reagle** [comment]
Yes, you are right about \times but it has a very different rendering on my system. u2717 matches the hand drawn quality of u2713, as you can see [here](http://reagle.org/joseph/2018/cda/talks/060-cooperation.html#/wisdom-of-crowds-woc-problem-domain). I think I'll create completions in the meantime.
