### ISSUE TITLE
Missing LaTeX synonyms: `\implies`, `\iff`, `\to`

### ISSUE THREAD

**Issue by ViktorQvarfordt** [randy3k/UnicodeCompletion#5]
The follow synonyms are missing.
`\implies` : `\Longrightarrow`
`\iff` : `\Longleftrightarrow`
`\to` : `\rightarrow`
Perhaps there are more. Some exist by default in LaTeX, some are defined by the `amsmath` package. If the intention of this package is to cover LaTeX symbols (which it seems to be), then I think these should be included. These symbols are used a lot by anyone writing mathematics (and I like to use unicode in my `.tex` files or emails.)

**Comment by randy3k** [comment]
I was using the resources from Julia to generate those unicodes. If you know of any other resources / websites / links, please let me know. I am very happy to merge them into this package.

**Comment by ViktorQvarfordt** [comment]
Nothing that I know of, perhaps these can be added manually. I don't think there are many more commands missing.

It would be nice if Julia had these synonyms as well. Perhaps I should create an issue over at Julia.

**Comment by randy3k** [comment]
> Perhaps I should create an issue over at Julia.

👍

**Comment by ViktorQvarfordt** [comment]
https://github.com/JuliaLang/julia/pull/21495

**Comment by randy3k** [comment]
Closed by 21621a1eccc80d47aa5eedca2b721368ba0ddf4b
