### ISSUE TITLE
UnicodeCompletion vs UnicodeMath

### ISSUE THREAD

**Issue by robinrosenstock** [randy3k/UnicodeCompletion#9]
What exactly is the difference between `UnicodeCompletion` and `UnicodeMath`?

**Comment by randy3k** [comment]
Apparently, UnicodeMath is more ambiguous in getting most of the unicode completions. But UnicodeCompletion has only a subset of all the unicodes which are maintained by the Julia community. Also, there seems to be no ways to disable UnicodeMath for a particular view/syntax.

**Comment by robinrosenstock** [comment]
ok, thank you for your reply, maybe UnicodeMath fits more my needs at the moment.
